// HostCore impl — bootstrap order per docs/05 §9.
//   Logger → Settings → EventBus → Tray → Keyring → CryptoPool →
//   PluginManager(per-plugin HostServices wrappers).
// Shutdown reverses this; Keyring::clearMemory zeroizes the process-static
// master cache after the crypto pool drops its in-memory copy.

#include "HostCore.h"

#include "paths/Paths.h"
#include "host/security/Keyring.h"
#include "host/services/QmlServiceImpl.h"
#include "host/ui/AppIconProvider.h"

#include <Margin/QmlService.h>

#include <QCoreApplication>
#include <QFont>
#include <QFontDatabase>
#include <QLocale>
#include <QObject>
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include <QQmlError>
#include <QString>
#include <QTranslator>
#include <QWindow>
#include <QTimer>
#include <QUrl>

#include <exception>
#include <vector>

namespace Margin {

HostCore& HostCore::instance() {
    static HostCore inst;
    return inst;
}

HostCore::~HostCore() = default;

bool HostCore::bootstrap() {
    Paths::ensureDirs();
    m_logger = std::make_unique<LoggerImpl>(Paths::logs());
    m_settings = std::make_unique<SettingsImpl>(Paths::config());
    applyLogLevel();
    m_eventBus = EventBus::wire();
    m_tray = std::make_unique<SystemTray>();
    m_tray->show();
    m_logger->info(QStringLiteral("host"), QStringLiteral("Margin v0.1.0 starting"));
    m_logger->info(QStringLiteral("host"), QStringLiteral("tray ready"));
    m_logger->info(QStringLiteral("host"), QStringLiteral("eventbus ready"));

    // Platform backend (lock screen on Win; nullptr on macOS until §A15 lifts).
    // Must precede PluginManager — AuraLockerPlugin reads host->lock() on onLoad,
    // and M2 Screen Time reads host->windowMonitor().
    m_platformBackend = PlatformBackend::create();
    if (m_platformBackend) {
        m_logger->info(QStringLiteral("host"),
                       QStringLiteral("platform backend ready (lock + window monitor supported)"));
    } else {
        m_logger->warn(QStringLiteral("host"),
                       QStringLiteral("platform backend unavailable on this OS; lock()/windowMonitor() return nullptr"));
    }

    // Master key from OS keyring (Win DPAPI; Mac deferred to C6) + per-plugin
    // crypto pool. Must precede PluginManager — per-plugin HostServices
    // wrappers cache a CryptoService& from this pool (docs/05 §8.2).
    std::vector<uint8_t> masterKey;
    try {
        masterKey = Keyring::getOrCreateMasterKey();
    } catch (const std::exception& e) {
        m_logger->error(QStringLiteral("host"),
                        QStringLiteral("keyring failure: %1")
                            .arg(QString::fromUtf8(e.what())));
        return false;
    }
    m_cryptoPool = CryptoServicePool::create(std::move(masterKey));
    m_logger->info(QStringLiteral("host"), QStringLiteral("keyring master key loaded"));

    // Database (M2-C2). Open margin.db under Paths::data(). WAL + pragmas
    // applied inside DatabaseImpl::open. Must precede PluginManager —
    // Screen Time plugin onLoad calls ensureSchema(ctx.host->database()).
    // If open fails, we log + leave m_database null; plugins null-check.
    m_database = std::make_unique<DatabaseImpl>();
    if (m_database->open(Paths::dbFile())) {
        m_logger->info(QStringLiteral("host"),
                       QStringLiteral("database ready: %1").arg(Paths::dbFile()));
    } else {
        m_logger->error(QStringLiteral("host"),
                        QStringLiteral("database open failed: %1")
                            .arg(m_database->lastError()));
        m_database.reset();
    }

    // Engine + QmlService BEFORE plugins — plugins call
    // ctx.host->qml()->registerContextProperty(name, this) at onLoad so
    // their Q_PROPERTY/Q_INVOKABLE surfaces are visible to QML by the time
    // DashboardWindow.qml loads at the bottom of this bootstrap.
    m_engine = std::make_unique<QQmlApplicationEngine>();
    m_qmlService = std::make_unique<QmlServiceImpl>(m_engine.get());

    // PR3 round-2 #2b: register the app-icon image provider so QML can
    // bind `image://appicon/<encoded-exe-path>`. HostCore owns the engine;
    // ownership of the provider transfers to the engine via
    // addImageProvider. Must precede engine.load() — QML resolves the
    // "appicon" scheme at load time, not at first paint.
    m_engine->addImageProvider(
        QStringLiteral("appicon"), new AppIconProvider());
    m_logger->info(QStringLiteral("host"), QStringLiteral("qml engine ready"));

    // M4-C2: register bundled font faces BEFORE engine.load() so the QML that
    // resolves Theme.fontSans/fontMono (name-list) at render time finds Inter
    // and JetBrains Mono installed in the application's font database. Faces
    // are bundled via fonts.qrc (generated by cmake/fetch_fonts.cmake). A face
    // that didn't make it through fetch returns -1 here — we log warn and the
    // Theme stack falls back to the next family on the list (PingFang SC →
    // Cascadia Code → Consolas → system default).
    for (const char* path : {
         ":/fonts/Inter-Regular.ttf",
         ":/fonts/Inter-Medium.ttf",
         ":/fonts/Inter-SemiBold.ttf",
         ":/fonts/JetBrainsMono-Regular.ttf",
         ":/fonts/JetBrainsMono-Medium.ttf",
         }) {
        const int id = QFontDatabase::addApplicationFont(QString::fromUtf8(path));
        if (id < 0) {
            // Likely the fetch script couldn't reach the network at configure
            // time. Theme's name-list handles the substitution silently.
            m_logger->warn(QStringLiteral("host"),
                           QStringLiteral("font registration skipped (not bundled): %1")
                               .arg(QString::fromUtf8(path)));
            continue;
        }
        const QStringList families = QFontDatabase::applicationFontFamilies(id);
        m_logger->info(QStringLiteral("host"),
                       QStringLiteral("font registered: %1 → [%2]")
                           .arg(QString::fromUtf8(path),
                                families.join(QStringLiteral(", "))));
    }

    m_plugins = std::make_unique<PluginManager>(
        *m_logger, *m_eventBus, *m_settings, *m_tray, *m_cryptoPool);
    m_plugins->setTrayIntegration(m_tray.get());
    m_plugins->setPlatformBackend(m_platformBackend.get());
    m_plugins->setQmlService(m_qmlService.get());
    m_plugins->setDatabase(m_database.get());
    m_plugins->setWindowMonitorService(
        m_platformBackend ? m_platformBackend->windowMonitor() : nullptr);
    m_plugins->setInputMonitorService(
        m_platformBackend ? m_platformBackend->inputMonitor() : nullptr);
    m_plugins->loadAll({Paths::officialPlugins(), Paths::userPlugins()});

    // Dashboard tab + Settings page registries (docs/06 §3.1 + §4.6, docs/04
    // §7). Host contributes Overview/General/Appearance/About directly;
    // plugin-contributed entries are pulled via DashboardTabContributor /
    // SettingsPageContributor. Both registries are filled by
    // reemitRegistries(), which is also called from applyLanguage on
    // language change so C++ translated titles (QCoreApplication::translate
    // in registerHostTabs/registerHostPages and inside each plugin's
    // tabInfo()/pageInfo()) flip with the catalog.
    m_tabRegistry = std::make_unique<DashboardTabRegistry>();
    m_settingsRegistry = std::make_unique<SettingsRegistry>();
    reemitRegistries();
    m_logger->info(QStringLiteral("host"),
                   QStringLiteral("dashboard tabs: %1 entries")
                       .arg(m_tabRegistry->tabs().size()));
    m_logger->info(QStringLiteral("host"),
                   QStringLiteral("settings pages: %1 entries")
                       .arg(m_settingsRegistry->pages().size()));

    // Activity feed (docs/05 §11, docs/06 §4.2 "最近事件" card). Subscribes
    // to a curated set of EventBus topics; ring buffer of 20 exposed to
    // QML via `activityFeed` context property. Constructed after EventBus
    // is wired (subscribe in ctor) and before engine->load() so the QML
    // resolves `activityFeed.events` on first evaluation.
    // PR6: attachDatabase() replays the most recent 20 rows from
    // host_activity_events so the feed survives restarts. No-op when
    // m_database is null (open failed at bootstrap) — feed degrades to
    // in-memory.
    m_activityFeed = std::make_unique<ActivityFeed>(*m_eventBus);
    if (m_database) m_activityFeed->attachDatabase(*m_database);
    m_logger->info(QStringLiteral("host"), QStringLiteral("activity feed ready"));

    // Overlay registry (docs/06 §3.1 Layer 3, docs/04 §7). Aggregates plugin
    // OverlayContributor pointers; OverlayContainer.qml binds a Repeater to
    // overlayRegistry.activeOverlays. Poll cadence is 500ms — breaks are not
    // latency-sensitive, and polling across the DLL boundary is more stable
    // than signal-based notification (see OverlayContributor.h header).
    m_overlayRegistry = std::make_unique<OverlayRegistry>();
    int overlayCount = 0;
    m_plugins->forEachPlugin([&overlayCount, this](PluginInterface* p) {
        OverlayContributor* c = p->asOverlay();
        if (!c) return;
        m_overlayRegistry->addContributor(c);
        ++overlayCount;
    });
    m_logger->info(QStringLiteral("host"),
                   QStringLiteral("overlay contributors: %1").arg(overlayCount));

    // Dashboard main panel (docs/01 §3 DashboardWindow::load — the last
    // bootstrap step before exec). Loaded hidden; opened from the tray. The
    // status-bar version is sourced from CMake project(VERSION) via
    // MARGIN_VERSION and injected as the marginVersion context property
    // (docs/06 §4.1). The tab list is injected as `dashboardTabs` so QML's
    // TabBar + StackLayout can render host and plugin tabs through one path.
    m_engine->rootContext()->setContextProperty(
        QStringLiteral("marginVersion"), QString::fromLatin1(MARGIN_VERSION));
    // M5-C4d: log file path surfaced on Settings → About → Diagnostics
    // so users can find the log without guessing based on Paths::logs().
    m_engine->rootContext()->setContextProperty(
        QStringLiteral("logFilePath"), m_logger->path());
    m_engine->rootContext()->setContextProperty(
        QStringLiteral("dashboardTabs"), m_tabRegistry.get());
    m_engine->rootContext()->setContextProperty(
        QStringLiteral("activityFeed"), m_activityFeed.get());
    m_engine->rootContext()->setContextProperty(
        QStringLiteral("overlayRegistry"), m_overlayRegistry.get());
    // settingsRegistry feeds SettingsWindow.qml's sidebar ListView.
    m_engine->rootContext()->setContextProperty(
        QStringLiteral("settingsRegistry"), m_settingsRegistry.get());
    // M5-C4d: General-page QML bridge. Q_PROPERTY logLevel + Settings
    // persistence. Subscribe to Settings::onChange so a QML dropdown change
    // flows back through HostCore::applyLogLevel — no restart required.
    m_generalSettings = std::make_unique<HostGeneralSettings>(*m_settings);
    m_engine->rootContext()->setContextProperty(
        QStringLiteral("generalSettings"), m_generalSettings.get());
    m_settings->onChange(QStringLiteral("general.log_level"),
        [this](const QVariant&) { applyLogLevel(); });
    // PR6 round-2 #7 + PR1 fix: same pattern for language. Host catalogs are
    // compiled into :/i18n/host_<lang>.qm by cmake/build_i18n.cmake (which
    // replaced qt6_add_translations — see docs/15-A8 for why). applyLanguage
    // installs the right translator; retranslate refreshes QML bindings so
    // the whole UI flips live.
    m_translator = std::make_unique<QTranslator>();
    applyLanguage();
    m_settings->onChange(QStringLiteral("general.language"),
        [this](const QVariant&) { applyLanguage(); });
    // Autostart: HostGeneralSettings persists the user's intent to
    // general.auto_start. HostCore pushes it to the OS registry via the
    // platform backend. Win-only in practice — Mac/Linux backend is
    // nullptr so the call is skipped and the preference just persists.
    // Bootstrap write is idempotent (registry setter on equal state is
    // a no-op) so re-launching Margin doesn't churn the registry.
    if (m_platformBackend) {
        const bool autoStartOn = m_settings->get(
            QStringLiteral("general.auto_start"), QVariant(false)).toBool();
        m_platformBackend->setAutoStartEnabled(autoStartOn);
        m_settings->onChange(QStringLiteral("general.auto_start"),
            [this](const QVariant& v) {
                if (m_platformBackend) m_platformBackend->setAutoStartEnabled(v.toBool());
            });
    }
    m_engine->load(QUrl(QStringLiteral("qrc:/ui/DashboardWindow.qml")));
    if (m_engine->rootObjects().isEmpty()) {
        m_logger->error(QStringLiteral("host"),
                        QStringLiteral("dashboard QML failed to load"));
        return false;
    }
    m_logger->info(QStringLiteral("host"), QStringLiteral("dashboard ready"));

    // M4-C10 / M0-C10c: apply OS-native dark window chrome before the
    // dashboard is shown. Dashboard is opened later from the tray (QML
    // openDashboard), but the QWindow already has a native HWND after
    // engine->load() — DwmSetWindowAttribute takes effect immediately
    // and persists across show/hide. Win-only; Mac deferred per §A15.
    if (m_platformBackend) {
        QWindow* dashboardWindow =
            qobject_cast<QWindow*>(m_engine->rootObjects().constFirst());
        if (dashboardWindow) {
            m_platformBackend->applyDarkTitleBar(dashboardWindow);
        } else {
            m_logger->warn(QStringLiteral("host"),
                           QStringLiteral("dashboard root is not a QWindow — dark title bar skipped"));
        }
    }

    // Layer 3 overlay container. Loaded as a second root document — it lives
    // as its own Window so it can take the full screen above the dashboard.
    // Polling the OverlayRegistry every 500ms drives shouldShow() checks;
    // active overlays show up in the Repeater, dismissed ones drop out.
    //
    // DIAGNOSTIC DISABLE (2026-06-19): OverlayContainer blanked the screen at
    // startup on some machines even after the visible-binding fix. Temporarily
    // skip loading it entirely so we can confirm whether the overlay container
    // is the cause or whether something else is responsible. Re-enable after
    // root cause is confirmed.
    //
    // UPDATE 2026-06-19 (case B confirmed): OverlayContainer IS the cause. The
    // QML-binding approach (visible bound to overlayRegistry.activeOverlays)
    // was insufficient — Qt 6.5 binding eval timing on Windows leaks a brief
    // visible=true at startup. Rewritten to mirror RhythmToast's pattern:
    //   - QML has `visible: false` hardcoded (never flips from QML)
    //   - C++ calls showFullScreen()/hide() on this window in response to
    //     OverlayRegistry::activeOverlaysChanged signal (no polling).
    const size_t rootsBefore = m_engine->rootObjects().size();
    m_engine->load(QUrl(QStringLiteral("qrc:/ui/OverlayContainer.qml")));
    if (m_engine->rootObjects().size() != rootsBefore + 1) {
        m_logger->error(QStringLiteral("host"),
                        QStringLiteral("overlay container QML failed to load (rootObjects went %1→%2)")
                            .arg(rootsBefore)
                            .arg(m_engine->rootObjects().size()));
        return false;
    }
    m_overlayWindow = qobject_cast<QWindow*>(m_engine->rootObjects().constLast());
    if (!m_overlayWindow) {
        m_logger->error(QStringLiteral("host"),
                        QStringLiteral("overlay container root is not a QWindow"));
        return false;
    }
    // M4-C10: dark chrome on the overlay window too, same way as dashboard.
    if (m_platformBackend) {
        m_platformBackend->applyDarkTitleBar(m_overlayWindow);
    }
    // Verify the QML honored the `visible: false` directive — if this fires,
    // the QML has regressed to a binding-based visibility model and may blank
    // the screen. See docs/15-dev-gotchas.md §B5.
    if (m_overlayWindow->isVisible()) {
        m_logger->error(QStringLiteral("host"),
                        QStringLiteral("overlay container visible after load — "
                                       "QML regression, refusing to bootstrap"));
        return false;
    }
    // Imperative show/hide: respond to OverlayRegistry changes only. No 500ms
    // polling (the contributor's shouldShow() is itself polled by the registry
    // from a plugin-side QTimer; here we only react to the cached result).
    QObject::connect(m_overlayRegistry.get(), &OverlayRegistry::activeOverlaysChanged,
                     [this]() {
        if (!m_overlayWindow) return;
        const bool shouldShow = !m_overlayRegistry->activeOverlays().isEmpty();
        if (shouldShow && !m_overlayWindow->isVisible()) {
            m_overlayWindow->showFullScreen();
            m_overlayWindow->raise();
        } else if (!shouldShow && m_overlayWindow->isVisible()) {
            m_overlayWindow->hide();
        }
    });
    // Drive the registry's shouldShow() polling — breaks are not latency-
    // sensitive so 500ms is fine. (Polling the registry is separate from
    // showing the window; the registry emits activeOverlaysChanged only when
    // the active set actually changes, which the connect() above turns into
    // a single show/hide call.)
    m_overlayPollTimer = std::make_unique<QTimer>();
    m_overlayPollTimer->setInterval(500);
    QObject::connect(m_overlayPollTimer.get(), &QTimer::timeout,
                     m_overlayRegistry.get(), &OverlayRegistry::pollAll);
    m_overlayPollTimer->start();
    // Initial poll — covers the case where a plugin's onLoad put a contributor
    // into shouldShow()==true state before the timer's first tick.
    m_overlayRegistry->pollAll();
    m_logger->info(QStringLiteral("host"), QStringLiteral("overlay container ready"));

    // M5-C3: Settings window (Layer 2, docs/06 §4.6). Loaded as a third root
    // document — its own Window so it can take focus + size independently of
    // the dashboard. Same imperative-show pattern as OverlayContainer:
    //   - QML has `visible: false` hardcoded (no binding-based visibility)
    //   - C++ calls show()/raise()/requestActivate() via openSettings()
    //   - tray signal mirrors openDashboardRequested's wiring
    const size_t rootsBeforeSettings = m_engine->rootObjects().size();
    m_engine->load(QUrl(QStringLiteral("qrc:/ui/SettingsWindow.qml")));
    if (m_engine->rootObjects().size() != rootsBeforeSettings + 1) {
        m_logger->error(QStringLiteral("host"),
                        QStringLiteral("settings QML failed to load (rootObjects went %1→%2)")
                            .arg(rootsBeforeSettings)
                            .arg(m_engine->rootObjects().size()));
        return false;
    }
    m_settingsWindow = qobject_cast<QWindow*>(m_engine->rootObjects().constLast());
    if (!m_settingsWindow) {
        m_logger->error(QStringLiteral("host"),
                        QStringLiteral("settings root is not a QWindow"));
        return false;
    }
    if (m_platformBackend) {
        m_platformBackend->applyDarkTitleBar(m_settingsWindow);
    }
    // Regression guard: the QML must keep visible:false at load time
    // (docs/15 §B5 — same risk as OverlayContainer).
    if (m_settingsWindow->isVisible()) {
        m_logger->error(QStringLiteral("host"),
                        QStringLiteral("settings window visible after load — QML regression"));
        return false;
    }
    // Expose the settings root so DashboardWindow.qml's Ctrl+, Shortcut can
    // call openSettings() via the same QQuickWindow method DashboardWindow
    // exposes. QWindow is a QObject, so setContextProperty accepts it.
    m_engine->rootContext()->setContextProperty(
        QStringLiteral("settingsRoot"), m_settingsWindow);
    m_logger->info(QStringLiteral("host"), QStringLiteral("settings window ready"));

    // Tray → dashboard. Receiver is the root window so the connection is torn
    // down with the engine; invokeMethod calls the QML openDashboard() helper.
    QObject* dashboard = m_engine->rootObjects().constFirst();
    QObject::connect(m_tray.get(), &SystemTray::openDashboardRequested,
                     dashboard, [dashboard]() {
                         QMetaObject::invokeMethod(dashboard, "openDashboard");
                     });

    // Tray → settings. Receiver is the settings window (a QObject via QWindow)
    // so the connection is torn down with the engine. The QML openSettings()
    // helper on SettingsWindow.qml mirrors DashboardWindow.openDashboard.
    // pageId ("about" from tray About, "" from tray Settings/Ctrl+,) is
    // forwarded so the QML can pre-select the sidebar entry.
    //
    // Q_ARG uses QVariant (not QString): QML JS function declarations have no
    // type annotations, so Qt registers them as taking QVariant regardless of
    // the actual JS coercion at runtime. Using Q_ARG(QString, ...) fails to
    // match the QVariant metatype and invokeMethod silently returns false —
    // observed as "tray About/Settings does nothing" (PR1 regression).
    QObject::connect(m_tray.get(), &SystemTray::openSettingsRequested,
                     m_settingsWindow, [settingsWin = m_settingsWindow](const QString& pageId) {
                         QMetaObject::invokeMethod(settingsWin, "openSettings",
                             Qt::AutoConnection,
                             Q_ARG(QVariant, QVariant::fromValue(pageId)));
                     });

    return true;
}

void HostCore::shutdown() {
    // Idempotent: aboutToQuit is the canonical caller, but main.cpp's
    // QML-load-fail early return calls this manually (aboutToQuit does not
    // fire when app.exec() never runs). A second call after the first
    // completes must be a no-op.
    if (m_shutdownDone) return;
    m_shutdownDone = true;

    // Order per docs/11-roadmap.md M0-C7 + M0-C8 + M0-C10b + M1-C6a + M2-C2:
    //   1. tray hide       — instant visual feedback; closes click races
    //   2. plugin unload   — onUnload may publish goodbye, so EventBus must
    //                        still be alive (plugins hold HostServices* too)
    //   3. engine + qml    — engine borrows QmlService; QmlService must drop
    //                        before engine (it holds a raw QQmlEngine*).
    //                        Plugins registered themselves as context props
    //                        via QmlService — onUnload happens in step 2,
    //                        so step 3 sees only the engine's own refs.
    //   4. crypto pool drop — plugin keys + master key copy zeroized
    //   5. Keyring clearMemory — process-static master cache zeroized
    //   6. database close  — flushes WAL; safe now that plugins can't write
    //   7. EventBus stop   — no plugin remains to publish
    //   8. settings+logger — torn down only after the final log line
    //
    // Tab registry drops before the engine because it is bound to QML as a
    // context property — engine teardown first avoids dangling references.
    if (m_logger) m_logger->info(QStringLiteral("host"),
                                QStringLiteral("shutdown: hiding tray"));
    // Hide the tray (visual cue) but keep the SystemTray object alive until
    // after plugin unload — plugins call host->tray().refreshPluginMenu()
    // from onUnload (e.g. Rhythm's m_timer.stop() emits stateChanged which
    // the plugin forwards). Dropping m_tray first would leave that call on
    // a dangling reference (M4-C16 regression).
    if (m_tray) m_tray->hide();

    if (m_logger) m_logger->info(QStringLiteral("host"),
                                QStringLiteral("shutdown: unloading plugins"));
    m_plugins.reset();

    if (m_logger) m_logger->info(QStringLiteral("host"),
                                QStringLiteral("shutdown: dropping tray"));
    m_tray.reset();

    if (m_logger) m_logger->info(QStringLiteral("host"),
                                QStringLiteral("shutdown: closing dashboard"));
    m_overlayPollTimer.reset();
    // m_overlayWindow + m_settingsWindow are owned by m_engine; null the raw
    // pointers before the engine dies so the activeOverlaysChanged handler
    // and openSettings() can't deref them.
    m_overlayWindow = nullptr;
    m_settingsWindow = nullptr;
    m_qmlService.reset();
    m_engine.reset();
    m_overlayRegistry.reset();
    m_activityFeed.reset();
    m_tabRegistry.reset();
    m_settingsRegistry.reset();
    m_generalSettings.reset();

    if (m_logger) m_logger->info(QStringLiteral("host"),
                                QStringLiteral("shutdown: clearing crypto pool"));
    m_cryptoPool.reset();
    Keyring::clearMemory();

    if (m_logger) m_logger->info(QStringLiteral("host"),
                                QStringLiteral("shutdown: closing database"));
    m_database.reset();

    if (m_logger) m_logger->info(QStringLiteral("host"),
                                QStringLiteral("shutdown: stopping eventbus"));
    m_eventBus.reset();

    if (m_logger) m_logger->info(QStringLiteral("host"),
                                QStringLiteral("shutdown: dropping platform backend"));
    m_platformBackend.reset();

    if (m_logger) m_logger->info(QStringLiteral("host"),
                                QStringLiteral("shutdown complete"));
    m_settings.reset();
    m_logger.reset();
}

void HostCore::applyLogLevel() {
    if (!m_logger || !m_settings) return;

    const QString raw = m_settings->get(QStringLiteral("general.log_level"),
                                        QVariant(QStringLiteral("Info"))).toString().toLower();
    if      (raw == QLatin1String("debug")) m_logger->setMinimumLevel(Logger::Level::Debug);
    else if (raw == QLatin1String("warn"))  m_logger->setMinimumLevel(Logger::Level::Warn);
    else if (raw == QLatin1String("error")) m_logger->setMinimumLevel(Logger::Level::Error);
    else if (raw == QLatin1String("fatal")) m_logger->setMinimumLevel(Logger::Level::Fatal);
    else                                    m_logger->setMinimumLevel(Logger::Level::Info);
}

void HostCore::applyLanguage() {
    // Resolve the desired locale code. "auto" maps to QLocale::system()
    // — on a zh-CN Windows install that's "zh_CN", on en-US it's "en_US".
    // We only ship zh_CN + en catalogs, so we round both en_* and zh_*
    // variants down to our two-letter canonical ("en" / "zh_CN") via
    // QLocale::language() + bcp47Name. Falls through to no-translation
    // when the catalog is missing (Mac stub etc.) — UI then renders in
    // qsTr source language.
    if (!m_translator || !m_settings) return;

    QString stored = m_settings->get(QStringLiteral("general.language"),
                                     QVariant(QStringLiteral("auto"))).toString();
    if (stored.isEmpty()) stored = QStringLiteral("auto");

    QString target;
    if (stored == QLatin1String("auto")) {
        const QLocale sys = QLocale::system();
        if (sys.language() == QLocale::Chinese) {
            target = QStringLiteral("zh_CN");
        } else {
            // Default everything non-Chinese to the English catalog. The
            // catalog covers ~50 strings; uncovered strings keep their
            // qsTr source (mixed zh/en in our QML today).
            target = QStringLiteral("en");
        }
    } else {
        target = stored;  // "zh_CN" or "en"
    }

    // removeTranslator + installTranslator every call — even when target
    // is unchanged, because QTranslator caches lookup state after a load.
    // QCoreApplication takes ownership in a sense, but we hold a
    // unique_ptr for deterministic teardown order; remove + load + re-add
    // is the documented pattern for swapping catalogs at runtime.
    if (m_translator.get()) {
        qApp->removeTranslator(m_translator.get());
    }
    // QTranslator::load(:/i18n/host_<target>.qm) — resource path scheme
    // matches what cmake/build_i18n.cmake bundles (qresource prefix="/i18n"
    // + alias host_<lang>.qm). Returns false on missing catalog; that's not
    // an error — qsTr falls through to source.
    const QString qrcPath = QStringLiteral(":/i18n/host_") + target + QStringLiteral(".qm");
    if (m_translator->load(qrcPath)) {
        qApp->installTranslator(m_translator.get());
        if (m_logger) m_logger->info(
            QStringLiteral("host"),
            QStringLiteral("language: %1 catalog loaded").arg(target));
    } else {
        if (m_logger) m_logger->warn(
            QStringLiteral("host"),
            QStringLiteral("language: catalog %1 not bundled; falling back to source").arg(qrcPath));
    }

    // Retranslate QML so bindings re-evaluate qsTr(). Without this, the
    // translator swap is silent until the next QML load. Qt 6.2+ exposes
    // QQmlApplicationEngine::retranslate for exactly this case.
    //
    // Order matters: install plugin translators BEFORE reemitting the
    // registries so plugin tab/page titles resolve via the freshly-loaded
    // :/<plugin_id>/i18n/<plugin_id>_<lang>.qm catalog. reemitRegistries
    // calls each plugin's tabInfo()/pageInfo() which use
    // QCoreApplication::translate("<PluginName>Plugin", ...); that lookup
    // walks qApp's translator stack in install order. Plugin translators
    // stack on top of host translator so plugin-only contexts (e.g.
    // AuraLockerPlugin) resolve via the plugin catalog and shared contexts
    // (e.g. SettingsPages) still hit the host catalog.
    if (m_plugins) {
        m_plugins->setLanguage(target);
    }
    //
    // Next: re-fresh the C++ side (registries' tab/page titles + tray menu)
    // so QML ListView and SystemTray already carry the new strings by the
    // time retranslate() fires its binding re-eval. Calling retranslate
    // before the registries are re-emitted leaves a one-frame race where
    // QML shows fresh qsTr output but stale tab titles pulled from the
    // registry cache.
    if (m_tabRegistry && m_settingsRegistry) {
        reemitRegistries();
    }
    // Activity feed titles render via QCoreApplication::translate("ActivityFeed",
    // ...) at insertion time (see ActivityFeed::renderTitle), so the cached
    // entries in m_events go stale on language change. retranslate() walks
    // the buffer and re-renders, then emits eventsChanged so the QML
    // Repeater on OverviewTab re-reads modelData.title. Same C++-first
    // ordering as reemitRegistries above.
    if (m_activityFeed) m_activityFeed->retranslate();
    if (m_tray) m_tray->retranslate();
    if (m_engine) m_engine->retranslate();
}

void HostCore::registerHostTabs() {
    // PR3 i18n: title goes through QCoreApplication::translate("DashboardTabs",
    // ...) so the dashboard tab label flips with general.language. Context
    // name is semantic (not a class name) — the matching <context> entry in
    // i18n/host_{en,zh_CN}.ts carries the translation; lupdate doesn't scan
    // QCoreApplication::translate calls, so the entry is hand-maintained.
    m_tabRegistry->addTab({
        QStringLiteral("overview"),
        QCoreApplication::translate("DashboardTabs", "Today's Overview"),
        QUrl(QStringLiteral("qrc:/icons/tab-home.svg")),
        QUrl(QStringLiteral("qrc:/ui/OverviewTab.qml")),
        10,  // order: Overview=10, Aura=20, Screen Time=30, Rhythm=40
    });
}

void HostCore::registerHostPages() {
    // PR3 i18n: context "SettingsPages" groups the three host-owned sidebar
    // entries. Same hand-maintained .ts story as DashboardTabs above.
    m_settingsRegistry->addPage({
        QStringLiteral("general"),
        QCoreApplication::translate("SettingsPages", "General"),
        QUrl(QStringLiteral("qrc:/icons/settings.svg")),
        QUrl(QStringLiteral("qrc:/ui/SettingsGeneralPage.qml")),
        QStringLiteral("host"), 10,
    });
    m_settingsRegistry->addPage({
        QStringLiteral("appearance"),
        QCoreApplication::translate("SettingsPages", "Appearance"),
        QUrl(QStringLiteral("qrc:/icons/icon-appearance.svg")),
        QUrl(QStringLiteral("qrc:/ui/SettingsAppearancePage.qml")),
        QStringLiteral("host"), 20,
    });
    m_settingsRegistry->addPage({
        QStringLiteral("about"),
        QCoreApplication::translate("SettingsPages", "About"),
        QUrl(QStringLiteral("qrc:/icons/icon-info.svg")),
        QUrl(QStringLiteral("qrc:/ui/SettingsAboutPage.qml")),
        QStringLiteral("about"), 10,
    });
}

void HostCore::registerPluginTabsAndPages() {
    // Each plugin's tabInfo()/pageInfo() returns std::string title. Plugins
    // that want localization call QCoreApplication::translate("<PluginName>",
    // ...) inside their impl — the lookup walks every installed translator,
    // so host's host_<lang>.qm is sufficient even without plugin-specific
    // catalogs (PR3 strategy; PR2 will move these to per-plugin .qm files).
    m_plugins->forEachPlugin([this](PluginInterface* p) {
        if (DashboardTabContributor* tab = p->asDashboardTab()) {
            const auto info = tab->tabInfo();
            m_tabRegistry->addTab({
                QString::fromStdString(info.id),
                QString::fromStdString(info.title),
                info.icon,
                info.content_qml,
                info.order,
            });
        }
        if (SettingsPageContributor* page = p->asSettingsPage()) {
            const auto info = page->pageInfo();
            m_settingsRegistry->addPage({
                QString::fromStdString(info.id),
                QString::fromStdString(info.title),
                info.icon,
                info.content_qml,
                QStringLiteral("plugins"),
                info.order,
            });
        }
    });
}

void HostCore::reemitRegistries() {
    // Clear → re-register host entries → re-register plugin entries →
    // re-sort. Each addTab/addPage emits tabsChanged/pagesChanged, so QML
    // ListView rebuilds several times during a single reemit. Cost is
    // bounded (host=1 tab + 3 pages, plugins ≤ a handful) and correctness
    // wins over micro-optimizing signal batching.
    m_tabRegistry->clear();
    m_settingsRegistry->clear();
    registerHostTabs();
    registerHostPages();
    registerPluginTabsAndPages();
    m_tabRegistry->sortByOrder();
    m_settingsRegistry->sortByOrder();
}

void HostCore::openSettings() {
    // M5-C2 wires the registry + context property; M5-C3 loads the QML that
    // backs m_settingsWindow. Until then, this is a no-op for callers that
    // happen to find the hostCore context property.
    if (!m_settingsWindow) return;
    if (!m_settingsWindow->isVisible()) {
        m_settingsWindow->show();
        m_settingsWindow->raise();
        m_settingsWindow->requestActivate();
    }
}

} // namespace Margin
